-- AlterTable
ALTER TABLE "User" ALTER COLUMN "citizenship" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "mail_code" DROP NOT NULL,
ALTER COLUMN "middle_name" DROP NOT NULL,
ALTER COLUMN "province" DROP NOT NULL,
ALTER COLUMN "region" DROP NOT NULL,
ALTER COLUMN "street" DROP NOT NULL;
